# Generated by Django 2.2.5 on 2019-09-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
