# Generated by Django 2.2.5 on 2019-09-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playsession',
            old_name='started',
            new_name='last_activity',
        ),
        migrations.AlterField(
            model_name='playsession',
            name='used_cards',
            field=models.ManyToManyField(blank=True, null=True, to='api.Card'),
        ),
    ]
