# Generated by Django 2.2.5 on 2019-09-11 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20190911_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playsession',
            name='used_cards',
            field=models.ManyToManyField(blank=True, to='api.Card'),
        ),
    ]
