# Generated by Django 2.2.5 on 2019-09-11 20:31

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('api', '0005_auto_20190911_1941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaySession',
            new_name='Session',
        ),
    ]
