# Generated by Django 2.2.5 on 2019-09-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
