# Generated by Django 2.2.5 on 2019-09-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190912_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
