# Generated by Django 2.2.5 on 2019-09-12 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190912_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='api.Pack'),
        ),
    ]
