# Generated by Django 2.2.5 on 2019-09-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190913_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='title',
            new_name='word',
        ),
    ]
